/** Ambient quotes for the plan page — one pool, balanced buy / rent / invest voices. */
export const PLAN_WHISPERS: readonly string[] = [
  "It was never just numbers. It's numbers plus how you sleep at night.",
  "Every good decision here is really a bet on your next ten years.",
  "There's no wrong answer. There's only the one that fits your life.",
  "Under seven years, renting often wins. Over ten, owning catches up. In between, it depends on you.",
  "Equity builds slowly. Liquidity builds quietly.",
  "Mutual funds sahi hai — until the market has a bad Monday.",
  "SIPs are boring. Boring is underrated.",
  "The market doesn't care about your possession date.",
  "Renting + investing quietly beat a lot of mortgages. Nobody posts about it.",
  "Owning feels like arriving. Renting feels like passing through.",
  "Liquidity is a feature you only appreciate when you need cash fast.",
  "EMI is forced saving. Rent is optionality. Pick your discipline.",
  "Renting isn't throwing money away — you're paying to not fix the geyser at 2am.",
  "A 15-day notice from a landlord teaches you what flexibility really costs.",
  "An EMI you can't feel is safe. One you can feel runs your calendar.",
  "Rent buys you the option to leave. That's worth something too.",
  "The dream is the house. The fine print is the maintenance.",
  "Prepay when surplus is real, not aspirational.",
  "Property is patient money. Make sure you're patient too.",
  "The best loan is the one that ends before you stop earning.",
  "Extra EMIs today are tomorrow's peace of mind — if you can afford the tradeoff.",
  "Freedom from EMI is a raise you give yourself.",
  "Ghar toh ghar hota hai — until the EMI reminds you it's also a loan.",
  "My parents measured 'settled' in square feet.",
  "Some things a spreadsheet can't price. A place that's actually yours is one of them.",
];
