import type { PropertyCard } from "./types.ts";

export const SAMPLE_PROPERTIES: PropertyCard[] = [
  {
    id: "sample_1",
    title: "3BHK in Prestige Lakeside Habitat",
    area: "Whitefield",
    price: 14500000,
    price_per_sqft: 8200,
    bhk: 3,
    sqft: 1768,
    society_name: "Prestige Lakeside Habitat",
    hero_image: null,
    transparency_tags: ["below_median", "strong_docs", "metro_nearby"],
  },
  {
    id: "sample_2",
    title: "2BHK in Sobha Dream Acres",
    area: "Sarjapur Road",
    price: 8900000,
    price_per_sqft: 7400,
    bhk: 2,
    sqft: 1203,
    society_name: "Sobha Dream Acres",
    hero_image: null,
    transparency_tags: ["good_society", "price_stable"],
  },
  {
    id: "sample_3",
    title: "3BHK in Brigade Metropolis",
    area: "Mahadevapura",
    price: 16800000,
    price_per_sqft: 9500,
    bhk: 3,
    sqft: 1768,
    society_name: "Brigade Metropolis",
    hero_image: null,
    transparency_tags: ["premium_society", "high_sunlight", "above_median"],
  },
  {
    id: "sample_4",
    title: "2BHK in Salarpuria Sattva",
    area: "Electronic City",
    price: 6200000,
    price_per_sqft: 5800,
    bhk: 2,
    sqft: 1069,
    society_name: "Salarpuria Sattva Greenage",
    hero_image: null,
    transparency_tags: ["below_median", "metro_nearby"],
  },
];
